### ISSUE TITLE
404 is not handled

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#81]
I edited my message.. I didn't see that what I was looking for was below...

**Comment by lucernae** [comment]
@pierrealixt @Christiaanvdm 
I think we should treat this as part of the development process.

503 is a typical HTTP error, that means the load balancer can't find process which can handle the request. If you go to Rancher in Ford3 environment, we can see that the uwsgi has errors.
We should rather get this errors and put this put it as an issue, because it maybe because some of the features we developed doesn't get caught in unittests (maybe, we need to do migrate first or collectstatic first in the server).
This will help us clearly separate what issues really from devops, or part of the feature development.

**Comment by lucernae** [comment]
As for this issue, the errors is:

```
Traceback (most recent call last):
3/11/2019 1:54:45 PM  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
3/11/2019 1:54:45 PM    response = get_response(request)
3/11/2019 1:54:45 PM  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 111, in _get_response
3/11/2019 1:54:45 PM    resolver_match = resolver.resolve(request.path_info)
3/11/2019 1:54:45 PM  File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 520, in resolve
3/11/2019 1:54:45 PM    raise Resolver404({'tried': tried, 'path': new_path})
3/11/2019 1:54:45 PMdjango.urls.exceptions.Resolver404: {'tried': [[<URLResolver <module 'base.urls' from './base/urls.py'> (None:None) '^'>, <URLPattern '^$' [name='home']>]], 'path': 'favicon.ico'}
3/11/2019 1:54:45 PM
3/11/2019 1:54:45 PMDuring handling of the above exception, another exception occurred:
3/11/2019 1:54:45 PM
3/11/2019 1:54:45 PMTraceback (most recent call last):
3/11/2019 1:54:45 PM  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 108, in get_exception_response
3/11/2019 1:54:45 PM    response = callback(request, **{**param_dict, 'exception': exception})
3/11/2019 1:54:45 PMTypeError: custom_404() got an unexpected keyword argument 'exception'
3/11/2019 1:54:45 PM
3/11/2019 1:54:45 PMDuring handling of the above exception, another exception occurred:
3/11/2019 1:54:45 PM
3/11/2019 1:54:45 PMTraceback (most recent call last):
3/11/2019 1:54:45 PM  File "./core/wsgi.py", line 51, in application
3/11/2019 1:54:45 PM    return _application(environ, start_response)
3/11/2019 1:54:45 PM  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 142, in __call__
3/11/2019 1:54:45 PM    response = self.get_response(request)
3/11/2019 1:54:45 PM  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 78, in get_response
3/11/2019 1:54:45 PM    response = self._middleware_chain(request)
3/11/2019 1:54:45 PM  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 36, in inner
3/11/2019 1:54:45 PM    response = response_for_exception(request, exc)
3/11/2019 1:54:45 PM  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 46, in response_for_exception
3/11/2019 1:54:45 PM    response = get_exception_response(request, get_resolver(get_urlconf()), 404, exc)
3/11/2019 1:54:45 PM  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 111, in get_exception_response
3/11/2019 1:54:45 PM    response = handle_uncaught_exception(request, resolver, sys.exc_info())
3/11/2019 1:54:45 PM  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 129, in handle_uncaught_exception
3/11/2019 1:54:45 PM    return callback(request, **param_dict)
3/11/2019 1:54:45 PM  File "./core/urls.py", line 28, in handler500
3/11/2019 1:54:45 PM    'request': request,
3/11/2019 1:54:45 PM  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 59, in render
3/11/2019 1:54:45 PM    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
3/11/2019 1:54:45 PM  File "/usr/local/lib/python3.7/site-packages/django/template/context.py", line 270, in make_context
3/11/2019 1:54:45 PM    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
3/11/2019 1:54:45 PMTypeError: context must be a dict rather than Context.
```

From the errors above, it's clear that we have some issue in 404 handling views (which will not show up in DEBUG mode, because Django will show the error as html views in DEBUG mode, and will not execute 404 handling).

So, this is rather a code error, not devops.

**Comment by pierrealixt** [comment]
Here's the issue:
```
3/22/2019 8:38:39 AMdjango.urls.exceptions.NoReverseMatch: 
Reverse for 'project-list' not found.
'project-list' is not a valid view function or pattern name.
```
